#spring
spring:
  jackson.date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect